Starmade\APIBundle\Model\PlanetCollection:
  exclusion_policy: ALL
  xml_root_name: planets
  properties:
    planets:
      expose: true
      type: array<Starmade\APIBundle\Model\Planet>
      xml_list:
        inline: true
        entry_name: planet
    offset:
      expose: true
      type: integer
      xml_attribute: true
    limit:
      expose: true
      type: integer
      xml_attribute: true
  relations:
    -
      rel: self
      href:
        route: get_planets
        absolute: true
    -
      rel: planet
      href:
        route: get_planet
        absolute: true
        generator: templated_uri
        parameters:
          id: "{uniqueid}"
      attributes:
        templated: true
