Starmade\APIBundle\Model\FactionCollection:
  exclusion_policy: ALL
  xml_root_name: factions
  properties:
    data:
      expose: true
      type: array<Starmade\APIBundle\Model\Faction>
      xml_list:
        inline: true
        entry_name: faction
    offset:
      expose: true
      type: integer
      xml_attribute: true
    limit:
      expose: true
      type: integer
      xml_attribute: true
  relations:
    -
      rel: self
      href:
        route: get_factions
        absolute: true
    -
      rel: faction
      href:
        route: get_faction
        absolute: true
        generator: templated_uri
        parameters:
          id: "{uniqueid}"
      attributes:
        templated: true
