Starmade\APIBundle\Model\SpaceStationCollection:
  exclusion_policy: ALL
  xml_root_name: spacestations
  properties:
    spacestations:
      expose: true
      type: array<Starmade\APIBundle\Model\SpaceStation>
      xml_list:
        inline: true
        entry_name: spacestation
    offset:
      expose: true
      type: integer
      xml_attribute: true
    limit:
      expose: true
      type: integer
      xml_attribute: true
  relations:
    -
      rel: self
      href:
        route: get_spacestations
        absolute: true
    -
      rel: spacestation
      href:
        route: get_spacestation
        absolute: true
        generator: templated_uri
        parameters:
          id: "{uniqueid}"
      attributes:
        templated: true
