Starmade\APIBundle\Model\Blueprint:
  exclusion_policy: ALL
  xml_root_name: note
  properties:
    name:
      expose: true
      type: string
      groups: [standard, restapi]
    description:
      expose: true
      type: string
      groups: [standard, restapi]
    secret:
      expose: true
      type: string
      groups: [restapi]
    version:
      expose: true
      type: string
      until_version: 1.1
    new_version:
      expose: true
      type: string
      serialized_name: version
      since_version: 1.1
  relations:
    -
      rel: self
      href:
        route: get_blueprint
        parameters:
          id: expr(object.id)
        absolute: true