Starmade\APIBundle\Model\ServerCollection:
  exclusion_policy: ALL
  xml_root_name: servers
  properties:
    data:
      expose: true
      type: array<Starmade\APIBundle\Model\Server>
      xml_list:
        inline: true
        entry_name: server
    offset:
      expose: true
      type: integer
      xml_attribute: true
    limit:
      expose: true
      type: integer
      xml_attribute: true
  relations:
    -
      rel: self
      href:
        route: get_servers
        absolute: true
    -
      rel: server
      href:
        route: get_server
        absolute: true
        generator: templated_uri
        parameters:
          id: "{uniqueid}"
      attributes:
        templated: true
