Starmade\APIBundle\Model\Ship:
  exclusion_policy: ALL
  xml_root_name: ship
  properties:
    uniqueid:
        expose: true
        type: string
        groups: [standard, restapi]
    name:
      expose: true
      type: string
      groups: [standard, restapi]
    creatorid:
      expose: true
      type: string
      groups: [standard, restapi]
    mass:
      expose: true
      type: float
      groups: [standard, restapi]
    power:
      expose: true
      type: integer
      groups: [standard, restapi]
    shields:
      expose: true
      type: integer
      groups: [standard, restapi]
    sector:
      expose: true
      type: array
      groups: [standard, restapi]
    aiconfig:
      expose: true
      type: array
      groups: [standard, restapi]
    secret:
      expose: true
      type: string
      groups: [restapi]
    version:
      expose: true
      type: string
      until_version: 1.1
    new_version:
      expose: true
      type: string
      serialized_name: version
      since_version: 1.1
  relations:
    -
      rel: self
      href:
        route: get_ship
        parameters:
          id: expr(object.uniqueid)
        absolute: true