Starmade\APIBundle\Model\Planet:
  exclusion_policy: ALL
  xml_root_name: planet
  properties:
    uniqueid:
        expose: true
        type: string
        groups: [standard, restapi]
    faction:
        expose: true
        type: integer
        groups: [standard, restapi]
    sector:
        expose: true
        type: array
        groups: [standard, restapi]
    secret:
      expose: true
      type: string
      groups: [restapi]
    version:
      expose: true
      type: string
      until_version: 1.1
    new_version:
      expose: true
      type: string
      serialized_name: version
      since_version: 1.1
  relations:
    -
      rel: self
      href:
        route: get_planet
        parameters:
          id: expr(object.uniqueid)
        absolute: true
    -
      rel: faction
      href:
          route: get_faction
          parameters:
            id: expr(object.faction)
          absolute: true