Starmade\APIBundle\Model\BlueprintCollection:
  exclusion_policy: ALL
  xml_root_name: blueprints
  properties:
    blueprints:
      expose: true
      type: array<Starmade\APIBundle\Model\Blueprint>
      xml_list:
        inline: true
        entry_name: blueprint
    offset:
      expose: true
      type: integer
      xml_attribute: true
    limit:
      expose: true
      type: integer
      xml_attribute: true
  relations:
    -
      rel: self
      href:
        route: get_blueprints
        absolute: true
    -
      rel: blueprint
      href:
        route: get_blueprint
        absolute: true
        generator: templated_uri
        parameters:
          id: "{uniqueid}"
      attributes:
        templated: true
