NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

_blueprints:
    resource: "@APIBundle/Controller/BlueprintsController.php"
    type:     rest
_ships:
    resource: "@APIBundle/Controller/ShipsController.php"
    type:     rest