NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

_blueprints:
    resource: "@APIBundle/Controller/BlueprintsController.php"
    type:     rest

_ships:
    resource: "@APIBundle/Controller/ShipsController.php"
    type:     rest

_shops:
    resource: "@APIBundle/Controller/ShopsController.php"
    type:     rest
    
_planets:
    resource: "@APIBundle/Controller/PlanetsController.php"
    type:     rest
_spacestations:
    resource: "@APIBundle/Controller/SpaceStationsController.php"
    type:     rest